/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint32_t *pClkConReg = (uint32_t*)0x40023830;
    uint32_t *pPortAModReg = (uint32_t*)0x40020000;
    uint32_t *pPortCModReg = (uint32_t*)0x40020800;
    uint32_t *pPortAOutReg = (uint32_t*)0x40020014;
    uint32_t *pPortCInReg = (uint32_t*)0x40020810;

    //1.Enabling peripheral clock of port A
    *pClkConReg |= (1<<0);
    //2.Enabling peripheral clock of port C
    *pClkConReg |=(1<<2);

    //3.Setting mode of port A as output mode for pin5
    *pPortAModReg &= ~(3<<10);//reset 11 and 10 bits
    *pPortAModReg |= (1<<10);//set bit 10
    //4.Setting mode of port C as input mode for pin0
    *pPortCModReg &= ~(3<<0);

    while(1)
    {
		//5.Read the pin C0.
		uint8_t pinStatus = (uint8_t*)(*pPortCInReg & 0x1);
		if(pinStatus)
		{
			*pPortAOutReg |= (1<<5);//turn on LED
		}else
		{
			*pPortAOutReg &= ~(1<<5);//turn off LED
		}
    }
}
